#
# zephyr.toml - Zephyr default prompt theme
#

add_newline = true

# A minimal left prompt
format = """$all"""

# move the rest of the prompt to the right
#right_format = """$status$git_branch${custom.git_status_dirty}$git_status"""
right_format = """$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status"""

palette="cappuccin_mocha"

# Define custom colors
[palettes.cappuccin_mocha]
black = '#45475a'
blue = '#89b4fa'
cyan = '#94e2d5'
green = '#a6e3a1'
purple = '#b4befe'
red = '#f38ba8'
white = '#a9b1d6'
yellow = '#f9e2af'
pink = '#f5c2e7'

[palettes.tokyo_night]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
purple = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[palettes.tokyo_night_256]
black = '16'
blue = '111'
cyan = '117'
green = '149'
purple = '141'
red = '210'
white = '146'
yellow = '179'

[palettes.wombat]
black = '#000000'
blue = '#5da9f6'
cyan = '#82fff7'
green = '#b1e969'
purple = '#e86aff'
red = '#ff615a'
white = '#dedacf'
yellow = '#ebd99c'

[palettes.wombat_256]
black = '0'
blue = '75'
cyan = '123'
green = '149'
purple = '171'
red = '203'
white = '188'
yellow = '223'

[character]
success_symbol = "[❯](green)[❯](green)"
error_symbol = "[✗](bold yellow)[✗](bold red)"
vicmd_symbol = "[VI](bold yellow)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold green'

[directory]
style = "purple"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = ' [$symbol$branch]($style)'
style = 'red'

[git_status]
format = '( [\[$ahead_behind$stashed\]]($style))'
style = "green"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "white"
format="[$symbol]($style)"
shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'

[username]
disabled = false
format='[$user ]($style)'
style_user = 'bold red'

[package]
format = '[$symbol$version ]($style)'
